### ISSUE TITLE
Cloudbreak setup  breaks on redhat with error = "Client cannot access resource server"

### ISSUE THREAD

**Issue by cskmohan** [sequenceiq/cloudbreak-deployer#132]
I am trying to setup CloudBreak on Redhat Linux 7.0, but I am stuck with a popup error "Client cannot access resource server" while trying to login the url "http://x.x.x.x:3001/" with default credentials.

Kernel version : 3.10.0-229.14.1.el7.x86_64
Docker version 1.8.3,

> cbd doctor  says everything is ok 
===> Deployer doctor: Checks your environment, and reports a diagnose.
local version:1.0.3
latest release:1.0.3
docker command: OK
docker client version: OK
docker server version: OK

I have disabled SELinux and firewalld as well

I appreciate any sort of help to fix this, thank you.
Regards,
Mohan

**Comment by mhmxs** [comment]
Hi @cskmohan,

Sorry for the really late answer, and i hope you are over this issue already. `cbd doctor` command helps to detect regular problems.
