### ISSUE TITLE
Could not install the latest cbd with the "install" script

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/cloudbreak-deployer#169]
I can't install the latest cbd with the "install" script. No content could be found with the url: https://github.com/sequenceiq/cloudbreak-deployer/releases/download/v1.1.0/cloudbreak-deployer_1.1.0_Darwin_x86_64.tgz . Could someone take a look of this? Thanks!

**Comment by matyix** [comment]
1.1.0 is not released yet, for now you can use 1.0.3.

**Comment by ylvmw** [comment]
Actually, I'm working on some cloud provider development based on cloudbreak 1.1.0-RC. So could I just use cbd 1.0.3 for the develoment? Or I just need to modify the version in docker-compose.yml?

Thanks!

**Comment by lalyos** [comment]
dont edit by hand the generated docker-compose.yml. You can change env variables in the `Profile` and than `cbd regenerate` can generate the docker-compose.yml.

To see the possible list of env variables use `cbd env export`

**Comment by ylvmw** [comment]
Great, thank you very much! And do you have some guide on how to develop a cloud provider? Do we only need to work on the cloudbreak project or any other projects (uluwatu, shell, etc)?

**Comment by lalyos** [comment]
Here is a pointer, if you want to implement the Service Provider Interface: http://sequenceiq.com/cloudbreak-docs/latest/spi/

**Comment by ylvmw** [comment]
OK, thanks again!
