### ISSUE TITLE
Can't access Cloudbreak UI

### ISSUE THREAD

**Issue by amwittenberg** [sequenceiq/cloudbreak-deployer#176]
I've created an AWS instance, and I launched the instance with the Cloudbreak AMI. I'm able to configure the profile, but have to use the private IP as it is inside of a VPC and does not have a public IP. I'm able to run cbd start successfully, but when attempting to access the UI, I get a dns error. My network is connected with this VPC, and have no issues connecting to the instance itself. Docker shows  that the uluwatu container is running on port 3000 as well. 

If I write out the full DNS, the lookup fails. If I write out the IP, I get connection refused error.

**Comment by lalyos** [comment]
Please try to use the same ip address as you are using to ssh into the instance as `PUBLIC_IP`, and dont set PRIVATE_IP. let me know if it works that way.

**Comment by amwittenberg** [comment]
Still same connection refused error

**Comment by lalyos** [comment]
## version
Which cbd version are you using? `cbd --version` if on 1.0.x please update to 1.1.0 with `cbd update`

## regenerate
After changing the `Profile~ you have to run `cbd regenerate` to create a new docker-compose.yml, and than restart the deployment with `cbd kill` followed by a `cbd start`

## connection
If you can ssh with ip- address, than you should be able to reach the cloudbreak UI. Gradually check:

- if you are ssh-d into the instance can `curl` the url what `cbd login` prints?
- if you can `curl` that url but not in your browser, than its yout proxy/vpn settings. You have to open up those ports (3000, 3001, 8080, 8089)
