### ISSUE TITLE
create openstack cluster

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/cloudbreak-deployer#177]
Hello,

I want to create an openstack cluster, but I can't find any document about how to do it. So I just want to ask some questions here:
1. Do I need to download the image from somewhere and import it to openstack manually?
2. Is there anything else I need to do before create the cluster?

Thanks!

**Comment by lalyos** [comment]
Yes there is an openstack image you have to import

```
curl -L  https://atlas.hashicorp.com/api/v1/artifacts/sequenceiq/cloudbreak/openstack.image/21/file | tar -tz
```

than import it onto with `glance image-create --disk-format qcow2 --container-format bare ...`

than you can follow the docs: http://sequenceiq.com/cloudbreak-docs/release-1.1.0/openstack_pre_prov/

**Comment by ylvmw** [comment]
Thank! Could you also tell me what should be installed on the image? Docker? Anything else?

**Comment by lalyos** [comment]
That image is for the purpose that its ready to use. So you dont have to install anything on it. Even you on't even start instances from it. Cloudbreak will use that image to start instances which will form the hadoop cluster.
