### ISSUE TITLE
How to create a customized image.

### ISSUE THREAD

**Issue by xinhevm** [sequenceiq/cloudbreak-deployer#178]
Hi,
Could I have some guide about building an image like "pre-configured Cloudbreak deployer image"? Because we need to use vmdk as our image, need know what components needs to install in the image. Thanks a lot!

Xin

**Comment by lalyos** [comment]
Hi,

The  "pre-configured Cloudbreak deployer image" for other cloud providers are basically:
- install docker
- install Cloudbreak Deployer
- prepull the docker images, so `cbd start` is quick

So follow the steps below:
## Get Docker

You have 3 options:
- Use the [docker image from Marketplace](https://azure.microsoft.com/en-us/marketplace/partners/canonicalandmsopentech/dockeronubuntuserver1404lts/)
- Use `docker-machine` to create an instance on azure
- Do it all yourself: start from whatever image, install docker yourself.

Of course i would recommend to use the docker image from marketplace. You just click on the 
big green **Create Virtual Machine** and follow the instructions. There is also [docs](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-ubuntu-quickstart/#create-a-vm-with-the-docker-image-from-canonical-and-msopentech) guiding you.

## Install Cloudbreak Deployer

You can read the [on-prem](http://sequenceiq.com/cloudbreak-docs/latest/onprem/) docs. But once you have the docker instance from the previous step, its just an *unzip*:
```
curl -Ls public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_1.1.0_$(uname)_x86_64.tgz | sudo tar -xz -C /bin cbd
```

To check if the installation is succesfull:
```
$ cbd --version
Cloudbreak Deployer: 1.1.0
```

## [Optional] Warm-up with docker images

This is optional, you can skip it safely, it just makes the *first* start quicker.
```
mkdir cloudbreak-deployment
cd $_
cbd init
cbd start
```
This will download all the docker images needed for CloudbreakDeployer. But if ypu want to create a reusable image, Yo have to delete the Profile as it contains the actual ip address, which wont match new instances starting from that image.

```
rm Profile
```

You can create an image from this instance
