### ISSUE TITLE
AWS Credentials can not be created

### ISSUE THREAD

**Issue by jakovm** [sequenceiq/cloudbreak-deployer#179]
Hello,

I'm running an ec2 instance (centos 7) with the current cbd version 1.1.0
===> Deployer doctor: Checks your environment, and reports a diagnose.
local version:1.1.0
latest release:1.1.0
docker command: OK
docker client version: OK
docker server version: OK

After loging in into the UI (but the same issue is with the CLI) I receive the error: "Internal server error" AWS Credentials can not be created.
The AWS access details are correctly set up, the cbd could create the role correctly.

**Comment by lalyos** [comment]
Hi,

Just to clarify the issue:
- you are able to log in on the web ui 
- You see a couple of tepmlates/blueprints
- you try to do something, where you get the "AWS Credentials can not be created"

Which action are you trying to do when you receive that message? Creating a new AWS credentials?

**Comment by jakovm** [comment]
Hi lalyos,
yes, I can login into the UI and I can see some templates.
Then I want to create the credentials like here.
http://sequenceiq.com/cloudbreak-docs/latest/images/aws-credential.png 
After I click on the button "create credentials" the error message occur.

**Comment by lalyos** [comment]
on AWS the process is, that you need:
```
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=YYY
```
Which will be used to **assume** the role you are using on that form: `arn:aws:iam:01234567899012:role/cb-access`

So please make sure, that the AWS credentials are valid for `assumeRole`.
You can test it via the `aws` cli:
```
aws sts assume-role \
  --role-arn arn:aws:iam:01234567899012:role/cb-access \
  --role-session-name test \
  --external-id provision-ambari
```

**Comment by jakovm** [comment]
Hi lalyos, I used the root AWS Access key, after creating and using a new user (with admin access), I can create the credentials. Now it is working.
THANKS a lot!
Jakov
