### ISSUE TITLE
Connection timed out when create openstack cluster

### ISSUE THREAD

**Issue by xinhevm** [sequenceiq/cloudbreak-deployer#180]
Hi,
I want to create an openstack cluster, but met some questions what to ask you. When create cluster, cb raises an exception that 
com.sequenceiq.cloudbreak.service.stack.connector.OperationException: ConnectionException{message=java.net.ConnectException: Connection timed out, status=0}.
I saw from logs that the exception is caused by OpenStackSetup.verifyFlavors. 

About my setting
1. Upload pre-config openstack image to openstack.
2. In cb resource, instance type is "m1.small" which is the basic flavor in openstack. 
3. In cb credentials, endpoint is http://<IP>:5000/v2.0. But where the public key file from? Which host?

Thanks!

Xin

**Comment by bbihari** [comment]
Hi @xinhevm,

According to the error message, Cloudbreak couldn't connect to your OpenStack. I think the endpoint you set is wrong, please fill the IP address correctly.

Documentation about the ssh key:
http://sequenceiq.com/cloudbreak-docs/latest/openstack_pre_prov/
About the credential creation:
http://sequenceiq.com/cloudbreak-docs/latest/openstack_cb_ui/

**Comment by xinhevm** [comment]
Thanks bbihari for your reply.
I have download the openstack image whose type is raw, but I want to convert it to vmdk to let cloudbreak run on vsphere platform successfully. After convert it the image is broken, I am debugging the root cause. Another solution might need your help. If we know what the software must be installed in the image, we don't need to convert it, then cloudbreak can support more platform. Could you help give us more knowledge about how to build an image? Thanks

**Comment by lalyos** [comment]
To easy start with CloudbreakDeployer(cbd) with provide images for amazon/gcp/openstack.

If you want to use it on any other platform i would recommend to start from an image provided by your platform. What you really need to be able to use cbd is only **docker**.

So you can start whatever linux distro you orefer, install Docker on it. Than installong cbd is a single line:
```
curl -Ls public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_1.1.0_$(uname)_x86_64.tgz | sudo tar -xz -C /bin cbd
```
You can read more in the [on prem docs](http://sequenceiq.com/cloudbreak-docs/latest/onprem/#install-cloudbreak-deployer_1)

**Comment by xinhevm** [comment]
Hi Lalyos,

Actually, we have prepared cbd, then need to connect to openstack then deploy a cluster. We have a question that every node (called template?) need to install docker? Or just need a basic linux distro like ubuntu, centos7? Then every hadoop service like datanode, namenode will install in every node? So the openstack image you provide is just a cbd-deployer image, but not a cluster template image? 

Thanks

**Comment by mhmxs** [comment]
Hi @xinhevm,

Sorry for the late answer, the provided image is just a cbd-deployer image.
