### ISSUE TITLE
Connection timeout when provision cluster to OpenStack

### ISSUE THREAD

**Issue by kashin08** [sequenceiq/cloudbreak-deployer#213]
I can successfully create OpenStack credentials and verify it. (which means cloudbreak deployer can connect to my target OpenStack)
But when I provision cluster to OpenStack, I got an "connection timeout" exception.

I have no idea why I got "connection timeout" when stack creation stage.
Please guide me how to identity the root cause.

The calltrace is attached below. Is there anything i should provide to help on this?

-------------------------------------------------------------------------------------------------------------------------------
cloudbreak_1 | 2016-04-27 01:52:44,273 [reactorDispatcher-18] handleStackCreationFailure:152 ERROR c.s.c.c.f.s.p.a.StackCreationService - [owner:fe2450f6-bed3-48b8-908d-a47ae868ebf2] [type:STACK] [id:4] [name:test0427] Error during stack creation flow:
cloudbreak_1 | org.openstack4j.api.exceptions.ConnectionException: java.net.ConnectException: Connection timed out
cloudbreak_1 |  at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51) ~[openstack4j-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:189) ~[openstack4j-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:183) ~[openstack4j-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:32) ~[openstack4j-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.openstack.common.OpenStackSetup.verifyFlavors(OpenStackSetup.java:59) ~[cloud-openstack-1.2.4.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.openstack.common.OpenStackSetup.prerequisites(OpenStackSetup.java:50) ~[cloud-openstack-1.2.4.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.handler.ProvisionSetupHandler.accept(ProvisionSetupHandler.java:49) ~[cloud-reactor-1.2.4.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.handler.ProvisionSetupHandler.accept(ProvisionSetupHandler.java:21) ~[cloud-reactor-1.2.4.jar!/:na]
cloudbreak_1 |  at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]
cloudbreak_1 |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
cloudbreak_1 |  at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
cloudbreak_1 |  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at com.sun.proxy.$Proxy199.accept(Unknown Source) ~[na:na]
cloudbreak_1 |  at reactor.bus.EventBus$3.accept(EventBus.java:317) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.EventBus$3.accept(EventBus.java:310) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:72) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.routing.TraceableDelegatingRouter.route(TraceableDelegatingRouter.java:51) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.EventBus.accept(EventBus.java:591) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.EventBus.accept(EventBus.java:63) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160) [reactor-core-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:74) [reactor-core-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
cloudbreak_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
cloudbreak_1 |  at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
cloudbreak_1 | Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out
cloudbreak_1 |  at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[jersey-common-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 |  at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 |  at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:86) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 |  ... 32 common frames omitted

**Comment by schfeca75** [comment]
Hi @kashin08,

Which version of Openstack do you use (Juno, Kilo)?

**Comment by schfeca75** [comment]
Could you please execute the following curl and send me the result:

```
curl -o <outputFile> -H "Content-Type: application/json" -d '
{
  "auth": {
    "tenantName": "<tenantId>",
    "passwordCredentials": {
      "username": "<userName>",
      "password": "<password>"
    }
  }
}' http://<openstack ip address>:5000/v2.0/tokens
```

**Comment by kashin08** [comment]
Hi @schfeca75 ,

Very thanks for your hint.
After executing the command you mentioned, I found the OpenStack service endpoint's IP is not accessible by cloudbreak-deployer. And now the cluster provision works fine after correcting the OpensStack endpoint setting.

Thank you again!

**Comment by schfeca75** [comment]
Your welcome!
