### ISSUE TITLE
java.net.UnknownHostException: controller

### ISSUE THREAD

**Issue by taotiewang** [sequenceiq/cloudbreak-deployer#225]
Infrastructure creation failed. Reason: java.net.UnknownHostException: controller

**Comment by mhmxs** [comment]
Hi @taotiewang ,

Could you please share more information about your environment?

- What version of deployer do you use?
- What command did you execute?
- What were the parameters?
- What kind of OS do you use?

Thanks,
Richard

**Comment by taotiewang** [comment]
My cloud is openstack kilo, on deployer ui, parameter of "create credentials":
![create credentials](https://cloud.githubusercontent.com/assets/2562272/15603122/99fe4842-242b-11e6-8a37-cf5d2381a69e.png)


What version of deployer do you use?
--cloudbreak-deployer-1.2.1, download cloudbreak-deployer-121-2016-04-08.img file
What command did you execute?
--on deployer ui, after "create credentials"、"create template"、"create network", then create and launch a new cluster

**Comment by taotiewang** [comment]
What kind of OS do you use?
--CentOS Linux release 7.2.1511 (Core)
What is the result of cbd doctor command?
--
![cbd doctor](https://cloud.githubusercontent.com/assets/2562272/15603284/639e697a-242c-11e6-9eba-d34d4e13b7ca.png)

**Comment by mhmxs** [comment]
Hi @taotiewang ,

I thought you have issue with the deployer itself, but seems it is related to Cloudbreak.
On the other hand as you see, you have some network issue, the deployer couldn't reach the internet. Are you behind a proxy for example?

**Comment by taotiewang** [comment]
There is no proxy

**Comment by mhmxs** [comment]
What are the result of `ping 8.8.8.8` and `curl -sf https://github.com > /dev/null && echo $?` commands?
