### ISSUE TITLE
Infrastructure creation failed. Reason: null

### ISSUE THREAD

**Issue by taotiewang** [sequenceiq/cloudbreak-deployer#227]
when create cluster in deployer, report NullPointerException:
![nullpointer](https://cloud.githubusercontent.com/assets/2562272/15735547/49868294-28cc-11e6-915b-de4f8d950cae.png)

**Comment by martonsereg** [comment]
Do you have Heat enabled on Openstack?
You can try to use the native openstack implementation that do not use heat. You can enable it by clicking the checkbox when creating the cluster.
Check this issue: https://github.com/sequenceiq/cloudbreak-deployer/issues/212
