### ISSUE TITLE
Modify the ambari-server and ambari-agent 

### ISSUE THREAD

**Issue by jsfeutz** [sequenceiq/cloudbreak-deployer#236]
cbd version 1.3.0
centos: 7
deploying to DC/OS Marathon

I need to create or modify the ambar-server and agent models used by cloudbreak to get out of http_proxy hell as well as different tools I need to add to the container. 

default_images:
hortonworks/ambari-server:2.2.1-v20
hortonworks/ambari-agent:2.2.1-v20 

Id like to replace them with
internal-repo.myco.com/dev/ambari-server:2.2.1-local
internal-repo.myco.com/dev/ambari-agent:2.2.1-local

How do I tell cloudbreak to use the my mod'd containers? I've tried both the CB_DOCKER_CONTAINER_AMBARI and CB_DOCKER_CONTAINER_AMBARI_WARM vars and doesnt seem to change anything 

Thanks in Advance,
@jsfeutz

**Comment by mhmxs** [comment]
Duplicated https://github.com/sequenceiq/cloudbreak/issues/1718
