### ISSUE TITLE
cbd-init fails in proxy environment

### ISSUE THREAD

**Issue by kedmison** [sequenceiq/cloudbreak-deployer#261]
cbd-init seems to always go through the network-doctor function, which assumes that ping is allowed directly to the public internet.  In several enterprises, this is not actually allowed.  

One suggestion might be to modify network-doctor to perform http-based tests that would use the proxy definitions.

**Comment by lalyos** [comment]
hmmm, doctor is "included" in init, to fail fast, so im reluctant to remove it completely.
How about if we detect a `http_proxy` we exclude the "network_doctor" part.
Would it work?

**Comment by kedmison** [comment]
I see the value of a network-doctor, for most users, so I share your reluctance to remove it entirely.

With the wide range of places that proxies have to be tweaked (yum.conf, shell, docker configs, etc) I can see that it's a longer path to try to find them all.  it's a struggle that we proxied folk are unfortunately used to but we would greatly appreciate a future effort to extend network-doctor to properly test proxied environments.

**Comment by lalyos** [comment]
looks like we have just comentend in the same minute .. ;)
So how about the `SKIP_NETWORK_DOCTOR` env var? You can put it into your Profile, and wont affect anything others, so its even backward compatible.

**Comment by lalyos** [comment]
regarding:
> future effort to extend network-doctor to properly test proxied environments

PRs are always welcome ;) Its pretty much bash script: https://github.com/sequenceiq/cloudbreak-deployer/blob/29af0f1879d249a43b781784aeffc54a5357118f/include/deployer.bash#L250

But even if you could describe what would make sense to check in proxied env please give a list

**Comment by lalyos** [comment]
Its fixed on master branch, you can give it a try:
```
cbd update master
echo 'export SKIP_NETWORK_DOCTOR=true' >> Profile
```
