### ISSUE TITLE
Cloudbreak-deployer GCP image error

### ISSUE THREAD

**Issue by varun-tdt** [sequenceiq/cloudbreak-deployer#279]
I am creating a GCP Cloudbreak-deployer n1-standard-2 instance using following image url gs://sequenceiqimage/cloudbreak-deployer-161-2016-11-07.tar.gz. Using the steps given in [Cloudbreak GCP](http://sequenceiq.com/cloudbreak-docs/latest/gcp/) page

The instance is not booting properly.

Serial port output shows :

```
SeaBIOS (version 1.8.2-20160912_142702-google)
Total RAM Size = 0x00000001e0000000 = 7680 MiB
CPUs found: 2     Max CPUs supported: 2
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=62914560 = 30720 MiB
drive 0x000f4730: PCHS=0/0/0 translation=lba LCHS=1024/255/63 s=62914560
Booting from Hard Disk 0...
```

**Comment by mhmxs** [comment]
Hi @varun-tdt,

First of all sorry for the late answer. Has you tried any newer image to run deployer? We have a newer image called `cloudbreak-deployer-162-2017-01-17.tar.gz`. Could you please make a try with it?

**Comment by mhmxs** [comment]
I tried cloudbreak-deployer-160-2016-11-07.tar.gz, cloudbreak-deployer-161-2016-11-07.tar.gz, cloudbreak-deployer-162-2017-01-17.tar.gz. Please reopen the issue if you have still problems.
