### ISSUE TITLE
cbd init - just stops working while downloading dependency

### ISSUE THREAD

**Issue by bwestpha** [sequenceiq/cloudbreak-deployer#316]
Hey guys,

I followed the installation instructions on http://sequenceiq.com/cloudbreak-docs/latest/onprem/ and I just want to initialize my Profil. But that didn't work so far because cbd just stops working while "installing" the missing dependency 'sed'.

Here the trace of it:

```
[usr@machine bin]# TRACE=1 cbd init
+ cbd-find-root
+ CBD_ROOT=/home/cloud/cloudbreak-deployment/.deps/bin
+ color-init
+ for color in '"${!color_table[@]}"'
+ eval 'yellow-bright() { color-cat yellow-bright; }'
+ for color in '"${!color_table[@]}"'
+ eval 'white-bright() { color-cat white-bright; }'
+ for color in '"${!color_table[@]}"'
+ eval 'gray() { color-cat gray; }'
+ for color in '"${!color_table[@]}"'
+ eval 'purple-bright() { color-cat purple-bright; }'
+ for color in '"${!color_table[@]}"'
+ eval 'yellow() { color-cat yellow; }'
+ for color in '"${!color_table[@]}"'
+ eval 'red() { color-cat red; }'
+ for color in '"${!color_table[@]}"'
+ eval 'blue() { color-cat blue; }'
+ for color in '"${!color_table[@]}"'
+ eval 'white() { color-cat white; }'
+ for color in '"${!color_table[@]}"'
+ eval 'green() { color-cat green; }'
+ for color in '"${!color_table[@]}"'
+ eval 'red-bright() { color-cat red-bright; }'
+ for color in '"${!color_table[@]}"'
+ eval 'blue-bright() { color-cat blue-bright; }'
+ for color in '"${!color_table[@]}"'
+ eval 'purple() { color-cat purple; }'
+ for color in '"${!color_table[@]}"'
+ eval 'cyan-bright() { color-cat cyan-bright; }'
+ for color in '"${!color_table[@]}"'
+ eval 'cyan() { color-cat cyan; }'
+ for color in '"${!color_table[@]}"'
+ eval 'green-bright() { color-cat green-bright; }'
+ load-profile init
+ CBD_PROFILE=Profile
+ '[' -f Profile ']'
+ [[ init != \i\n\i\t ]]
+ [[ -n '' ]]
+ deps-init
++ deps-dir
++ echo /home/cloud/cloudbreak-deployment/.deps/bin/.deps
+ export PATH=/home/cloud/cloudbreak-deployment/.deps/bin/.deps/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
+ PATH=/home/cloud/cloudbreak-deployment/.deps/bin/.deps/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
+ deps-require sed
+ declare name=sed version=latest
+ deps-check sed latest
+ declare name=sed version=latest
++ deps-dir
++ echo /home/cloud/cloudbreak-deployment/.deps/bin/.deps
+ [[ -f /home/cloud/cloudbreak-deployment/.deps/bin/.deps/bin/sed ]]
+ echo '* Dependency required, installing sed latest ...'
+ yellow
+ color-cat yellow
+ declare color=yellow
+ read -r
+ printf '\033[00;33m%s\033[0m\n' '* Dependency required, installing sed latest ...'
* Dependency required, installing sed latest ...
+ read -r
+ deps-install sed latest
+ declare name=sed version=latest
+ local tag index tmpdir tmpfile dep filename extension install
++ deps-dir
++ echo /home/cloud/cloudbreak-deployment/.deps/bin/.deps
+ mkdir -p /home/cloud/cloudbreak-deployment/.deps/bin/.deps/bin
++ curl -s https://raw.githubusercontent.com/lalyos/glidergun-rack/master/index/sed
+ index=
[usr@machine bin]#
```

As you can see, nothing really happens here and cbd just stops. 

I'm not able to use a predefined image so I only have the manual installation but it did not work. Any suggestions?

/// System:
CentOS Linux release 7.3.1611 (Core)
CBD 1.6.3
I 'm using a system proxy with authentification (if this migth be interesting)

**Comment by mhmxs** [comment]
Hi @bwestpha ,

Could you please paste here the output of `cbd doctor`command? Seems `curl -s https://raw.githubusercontent.com/lalyos/glidergun-rack/master/index/sed` is not available, but available for me so i suspect some network issue for the first view.

**Comment by bwestpha** [comment]
Hi @mhmxs ,

sure I an :) 

```
[usr@machine cloudbreak-deployment]# cbd doctor
!! No Profile found. Please initalize your 'Profile' with the init command.
cbd init
* Dependency required, installing sed latest ...
[usr@machine cloudbreak-deployment]#
```

So still nothing happens here.

If I use 'curl -s https://raw.githubusercontent.com/lalyos/glidergun-rack/master/index/sed' manually it works fine and gave me :

```
[usr@machine cloudbreak-deployment]# curl -s https://raw.githubusercontent.com/lalyos/glidergun-rack/master/index/sed
# install: chmod +x sed && mv sed $PREFIX/bin

latest linux_amd64 https://github.com/sequenceiq/docker-gnused-linux-bin/releases/download/v4.2.2/sed-linux-4.2.2.tgz a9404833974aea2356e2c984d30fed9e
latest darwin_amd64 https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz f0fb77edffd31acfa0e2916ba87f7f1a

4.2.2 linux_amd64 https://github.com/sequenceiq/docker-gnused-linux-bin/releases/download/v4.2.2/sed-linux-4.2.2.tgz a9404833974aea2356e2c984d30fed9e
4.2.2 darwin_amd64 https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz f0fb77edffd31acfa0e2916ba87f7f1a
[usr@machine cloudbreak-deployment]#
```


This is working because I already set the ENV variables with the proxy in /etc/profile

**Comment by mhmxs** [comment]
Hi @bwestpha 

It is interesting, because if you see [this](https://github.com/sequenceiq/cloudbreak-deployer/blob/rc-1.6/include/deps.bash#L29) line fails, which is `curl -s https://raw.githubusercontent.com/lalyos/glidergun-rack/master/index/sed`at runtime. Did you follow the instructions about [proxy settings](http://sequenceiq.com/cloudbreak-docs/master/operations/#proxy-settings)?

**Comment by bwestpha** [comment]
Should be fine I think:

```
[usr@machine cloudbreak-deployment]# echo $http_proxy
http://my_username:my_password@my_proxy.tld:8080
[usr@machine cloudbreak-deployment]# echo $https_proxy
http://my_username:my_password@my_proxy.tld:8080
[usr@machine cloudbreak-deployment]# echo $CB_HTTP_PROXY
http://my_username:my_password@my_proxy.tld:8080
[usr@machine cloudbreak-deployment]# echo $CB_HTTPS_PROXY
https://my_username:my_password@my_proxy.tld:8080
[usr@machine cloudbreak-deployment]# echo $CB_JAVA_OPTS
-Dhttp.proxyHost=http://my_username:my_password@my_proxy.tld -Dhttp.proxyPort=8080 -Dhttps.proxyHost=https://my_username:my_password@my_proxy.tld -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=172.17.0.1|*.service.consul|*.node.dc1.consul

```

So I think it should be set up well, right?

**Comment by mhmxs** [comment]
Hi @bwestpha, Deployer uses `Profile` file to store Cloudbreak specific environment variables, but doesn't inherit any (except a few) environment variable from the parent. That means you have create your own `Profile` file by hand with proxy settings in it and the default bind address or hostname called PUBLIC_IP. If you are done you don't need to execute `cbd init` command any more, because ini creates the Profile file :)

**Comment by bwestpha** [comment]
@mhmxs Okay.
Since the init-command does not working properly, do you have a empty 'Profile'-file I can work with?
The location of the "Profile-file" is whereever I want to? (so the same location I would execute the cdb init command?!)

And last but not least, is it really a "**P**rofile"-file oder a "**p**rofile"-file? 
Thanks in advance

**Comment by mhmxs** [comment]
Hi @bwestpha ,
cbd ini creates a file called Profile, dowloads deps and other. Where you executed will be the location of your Cloudbreak. Name is case sensitive. Because cbd init doesn't work behind proxy you have to create a text file called Profile, and fill with required variables, PUBLIC_IP plus proxy related things.
```
echo "export PUBLIC_IP=1.2.3.4" > Profile
```

**Comment by bwestpha** [comment]
Okay, really looks like it were mainly an PEBKAC error. Since icreated the file like you said, with all the proxy settings from my regular profile-file, it works. 


Now I am facing a new problem, but I think i will get that one by my own :) 

Thanks so much !

**Comment by mhmxs** [comment]
not at all
