### ISSUE TITLE
GCP cloudbreak-deployer-1140-2017-03-22 "port 22: Connection timed out"

### ISSUE THREAD

**Issue by craftyc0der** [sequenceiq/cloudbreak-deployer#326]
I have been unable to log in to cloudbreak-deployer if I use the prebuilt image. I've tried a couple of recent versions with no success.  I've passed in keys for a cloudbreak user. I've tried just using the SSH button in the GCP UI. Nothing connects. I cannot ping the server either. Firewall always allows port 22. gcloud ssh also fails.

The CPU starts out above 50% and stays there. 

This is a step zero problem. Can someone shed light on my foolishness?

**Comment by doktoric** [comment]
@craftyc0der 
somehow our tar file corrupted so I just burned a new image and tested with succes. 
Please try with the new image:
```
 gcloud compute images create cloudbreak-deployer-1140-2017-03-24 --source-uri gs://sequenceiqimage/cloudbreak-deployer-1140-2017-03-24.tar.gz
```

**Comment by craftyc0der** [comment]
Success. Thank you. Whatever the issue was, it has been with you for a while because I had the same issue with your February image as well. Have a nice day.
