### ISSUE TITLE
cbd init does not work with or wothout Profile

### ISSUE THREAD

**Issue by ckonstanski** [sequenceiq/cloudbreak-deployer#33]
Whether I have a Profile or not, cbd init refuses to run.

[WARN] We can not guess your PUBLIC_IP, please run the following command: (replace 1.2.3.4 with a real IP)
echo '1.2.3.4' > Profile

If I follow the directions by running:

root@wiretux:~/cloudbreak-deployment # echo $(ifconfig eth0 |grep -F 'inet ' |awk '{print $2;}') >Profile
root@wiretux:~/cloudbreak-deployment # cat Profile
172.16.161.128

Now I have a Profile that satisfies the instructions I was given. Trying cbd init again:

./Profile: line 1: 172.16.161.128: command not found

Assuming that you really meant that my Profile should contain:

export PUBLIC_IP=172.16.161.128

Manually made this change. Running cbd init again:

[WARN] Profile already exist, move away if you want to regenerate

It's a "damned if I do, damned if I don't" situation.

**Comment by lalyos** [comment]
Hi Carlos,

Thanks for reporting. You are right the instructions should be:
```
echo export '1.2.3.4' > Profile
```

Once you have the Profile, there is nothing to `init` you start to 
```
cbd generate
cbd pull
```

But the command should say something like:
> You already have a Profile, you can run `cbd generate` now

**Comment by lalyos** [comment]
You can test with a snapshot version:

```
cbd update master
cbd init
```

# Reproducing
Here is my test (reproducing your issue with 0.1.0)
```
$ echo export PUBLIC_IP=192.168.44.1>Profile                                                                                                
$ cbd init
[WARN] Profile already exist, move away if you want to regenerate
```

# testing the fix
```
$ cbd update master

Update /bin/cbd from: https://circle-artifacts.com/gh/sequenceiq/cloudbreak-deployer/123/artifacts/0/tmp/circle-artifacts.jXdpNpT/cbd-linux.tgz

$ cbd --version
CloudBreak Deployer: 0.1.0-master-d1eb594

$ cbd init
Profile already exist, now you are ready to run:
cbd generate
```

**Comment by ckonstanski** [comment]
Much appreciated! Worked.
