### ISSUE TITLE
Where to set Login for UI? 

### ISSUE THREAD

**Issue by dischord01** [sequenceiq/cloudbreak-deployer#35]
I successfully used cbd pull & cbd start, now when I go to the UI on http://52.6.83.114:3001/ I see the login screen. But did not see where to set the user+pass when setting it up. Does it use a default password?

**Comment by dischord01** [comment]
Nevermind, I see the signup on the Login.

**Comment by biharitomi** [comment]
Hi @dischord01 ,

You do not have to sign up, the email and password could be overwritten in your 'Profile', but they have default values and not mandatory to be defined in the 'Profile'. You can check all the defined config by using '***cbd env show***' (**UAA_DEFAULT_USER_EMAIL** and **UAA_DEFAULT_USER_PWD**).

Br,
Tamas

**Comment by lalyos** [comment]
You can see the default user/password is in the bottom of the `uaa.yml`
- user: `admin@example.com`
- pwd:`cloudbreak`

You can configure it via Profile:
```
export UAA_DEFAULT_USER_EMAIL=myself#example.com
export UAA_DEFAULT_USER_PW=demo123
```

To see all available configuration, with actual values
```
cbd env show
```

It needs more documentation in readme .... Im doing it right now

**Comment by dischord01** [comment]
Great thanks again!
