### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by ckonstanski** [sequenceiq/cloudbreak-deployer#37]
I got cbd running (thanks for all previous help!). Now I'm trying to sign up a new user. But the email never comes.

Can you tell me where the MTA is located so I can do some troubleshooting? Is it in one of the docker containers? Or does it use the host's MTA?

**Comment by lalyos** [comment]
Its "BringYourOwn" smtp service. If you don't configure SMTP, mails won't be sent, but they should be visible in the log `cbd logs`.

I would advise first you can try the hosted version of cloudbreak: https://cloudbreak.sequenceiq.com

To deploy your own cloudbreak makes more sense if you want to deploy tp a private Openstack for example. Otherwise if your target cloud is AWS/GCP/Azure its much easier to use the hosted version.

But to answer your question: You can set the 5 env variable as described at https://github.com/sequenceiq/cloudbreak-deployer#smtp

**Comment by ckonstanski** [comment]
I have to deploy my oun cloudbreak. This is a Hortonworks project, and they specified this as a requirement.

I will look at the environment variables. Actually I looked at the cloudbreak source project before discovering cloudbreak-deployer, and I wondered where the environment variables went. Thanks.

**Comment by ckonstanski** [comment]
I found the following in my logs. The environment valriable names do not match the doc:

SMTP not configured! Related configuration entries: SL_SMTP_SENDER_HOST,SL_SMTP_SENDER_PORT,SL_SMTP_SENDER_USERNAME,SL_SMTP_SENDER_PASSWORD,SL_SMTP_SENDER_FROM

I set my environment with these variables:

export PUBLIC_IP=192.168.245.248
export SL_SMTP_SENDER_USERNAME=
export SL_SMTP_SENDER_PASSWORD=
export SL_SMTP_SENDER_HOST=192.168.245.248
export SL_SMTP_SENDER_PORT=25
export SL_SMTP_SENDER_FROM=noreply@wirestone.com

My setup includes a local postfix that requires no authentication. It sends all email through a smarthost. I wanted to make things as simple as possible for cloudbreak.

Apparently the environment variables in my Profile are not being recognized. (I also tried with CLOUDBREAK_ env vars as per the doc, also to no avail.)

I did the usual telnet and echo | mail tests. My MTA is functioning properly.

**Comment by lalyos** [comment]
I see,

So smtp config in a bit more detail: 3 part of cloudbreak needs email config:
- cloudbreak-api: About the status of the stack changes: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/compose.bash#L132-L136
- sultans: the user registration api, so probably this is your concern: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/compose.bash#L164-L168
- periscope: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/compose.bash#L218-L222

Hmm while writing the references i just realised that sultans env are commented out. I'm fixing it now, and will inform you when you can if you have a snapsnop to try.

**Comment by ckonstanski** [comment]
Thanks. In the meantime I prepared my Profile with this redundant but explicit config:

export CB_SMTP_SENDER_USERNAME=
export CB_SMTP_SENDER_PASSWORD=
export CB_SMTP_SENDER_HOST=192.168.245.248
export CB_SMTP_SENDER_PORT=25
export CB_SMTP_SENDER_FROM=noreply@wirestone.com
export SL_SMTP_SENDER_USERNAME=
export SL_SMTP_SENDER_PASSWORD=
export SL_SMTP_SENDER_HOST=192.168.245.248
export SL_SMTP_SENDER_PORT=25
export SL_SMTP_SENDER_FROM=noreply@wirestone.com
export PERISCOPE_SMTP_SENDER_USERNAME=
export PERISCOPE_SMTP_SENDER_PASSWORD=
export PERISCOPE_SMTP_SENDER_HOST=192.168.245.248
export PERISCOPE_SMTP_SENDER_PORT=25
export PERISCOPE_SMTP_SENDER_FROM=noreply@wirestone.com

**Comment by lalyos** [comment]
Sorry but that won't help, as i was referring to the exact lines in docker-compose.ml files
Every container uses the `CLOUDBREAK_SMTP_XXX` set. So this way you don't need 15 variables only 5.

but exactly the sultans is commented ... i'll fix it soon

**Comment by ckonstanski** [comment]
OK, I understand. I'll fix my Profile.

**Comment by lalyos** [comment]
The latestt snapshot `0.1.0-master-a50c7c9` contains the fix for sultans
```
cbd update master
cbd --version
CloudBreak Deployer: 0.1.0-master-a50c7c9
```

**Comment by ckonstanski** [comment]
Grabbed the update. Email still doesn't work.

Trying different things to help the email issue. I tried changing CLOUDBREAK_SMTP_SENDER_HOST to 172.17.42.1 (the docker0 IP). I verified it by gaining a bash shell from within one of the docker containers and doing a ping. tcpdump showed that the pings were making it to the host. But I still see this error in the log:

SMTP not configured! Related configuration entries: SL_SMTP_SENDER_HOST,SL_SMTP_SENDER_PORT,SL_SMTP_SENDER_USERNAME,SL_SMTP_SENDER_PASSWORD,SL_SMTP_SENDER_FROM

**Comment by lalyos** [comment]
Lets try to use irc: freenode #cloudbreak I'm waiting there ...

**Comment by ckonstanski** [comment]
OK, give me a minute: I haven't used IRC in a coon's age. Need to install something.

**Comment by lalyos** [comment]
https://webchat.freenode.net

**Comment by ckonstanski** [comment]
Solved! Thanks for your help.
