### ISSUE TITLE
cannot start container : System error: not a directory

### ISSUE THREAD

**Issue by saurabhsurana** [sequenceiq/cloudbreak-deployer#39]
When I do cbd start, it downloads images for various components but while starting the containers it gives error like this one:

Status: Downloaded newer image for sequenceiq/uaa:1.8.1-v1
Cannot start container 3dbfab260ec2803fc0d62840548b77fca9404abd4f48012fd4bbd11b4f296c9b: [8] System error: not a directory

This didn't happen before when I tried this few days back, I could see pretty much all the containers come up fine. I tried this on multiple different machines and I am getting the same issue everywhere now.

**Comment by lalyos** [comment]
hi Saurabh,

Sorry for the slow response,last week week was rather busy ...

## Short Answer
you need `cbd generate`

# Long Answer

If `cbd generate` didn't solve your problem, or you are interested in the *why*
read on:

## check bcd version
Please make sure you have the latest release of cbd
```
$ cbd update
$ cbd --version
> CloudBreak Deployer: 0.1.0
```

## Missing generated identity configuration

The error message means, you are missing the `uaa.yml` file. It is the generated
configuration of the identity server. 

For the  0.1.0 release, it needs this step:
```
cbd generate
```

Please note that the next version cbd (0.1.1 not released yet) is already doing `cbd generate`
automatically if `uaa.yml` is missing. Thats why the README don't mentions `cbd generate`.

**Comment by lalyos** [comment]
I'm closing this issue as it seems to be solved. Please reopen it if you still have it.

**Comment by rmarshasatx** [comment]
I'm encountering the same problem that saurabhsurana had in April. I have tried every combination of cbd generate/update/regenerate. I keep getting the error: "Cannot start container 0eb8d81b096628d744e62e14ec351acf7f5323e5eb2bbcf4891b97d370138bf8: [8] System error: not a directory". The uaa.yml file is present. Attempting to login at the URL with credentials provided by the cbd login command produces the error: "Client cannot access resource server." cbd doctor displays the version number 0.5.3 with OK's for all boot2docker and docker items. cbd ps shows that cbreak_ambassadorips_1 has an exit 0 status while cbreak_identity_1 has an exit -1 status. Ideas?

**Comment by lalyos** [comment]
@rmarshasatx please come to this hipchat channel to solve it: https://www.hipchat.com/gohd6v0n1
(no registration/installation needed just open in a browser)
