### ISSUE TITLE
Periscope and cloudbreak containers exit with errors "Missing table:" Ambari and Blueprint

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#48]
Hi,

I was trying to deploy cloudbreak in my local system and I followed the Readme.md and managed to start all the docker containers. The cloudbreak UI is accessible, but after a while both the cloudbreak and periscope containers exit with status 1.

![screenshot from 2015-05-06 18 13 27](https://cloud.githubusercontent.com/assets/2684148/7493129/b6c2abc6-f41b-11e4-8d66-74d87cf29ca1.png)

When I checked the docker logs of periscope, it exited with error message "Missing table: Ambari"  and cloudbreak exits probably due to the error "Missing table: Blueprint". Can somebody please help me find out the problem? The complete log of both the docker containers can be found here:
https://www.dropbox.com/s/n9wscmcoyeo0nmu/logs.zip?dl=0

Thanks

**Comment by cs905s** [comment]
I had the same error after updating with __cbd update master__
I have reported it as an issue in sequenceiq/periscope.

Docker image: sequenceiq/periscope:0.5.2

__Missing field "ambari_host" in table public.ambari__

Meanwhile to get around this - went back to the earlier release (__cbd update__)

**Comment by lalyos** [comment]
@cs905s 
If you update cbd to master, you should get periscope: **0.5.3** not 0.5.2.

If you have generated the docker-compose.yml previously, cbd doesn't overwrites it,
you prints a warning that it has to be regenerated. (it might change, as it seems
it wasn't clear enought to do it)

So You have to regenerate the yaml files:

```
cbd update master
rm *.yml
cbd generate
cbd start
```

**Comment by malathit90** [comment]
@lalyos I just now tried the steps you mentioned and the error no longer occurs. Thanks for your help.
