### ISSUE TITLE
Documentation on Readme

### ISSUE THREAD

**Issue by cs905s** [sequenceiq/cloudbreak-deployer#53]
When running on a Amazon instance in a private subnet, cbd init fails with the error
*[WARN] We can not guess your PUBLIC_IP, please run the following command: (replace 1.2.3.4 with a real IP)*
__echo '1.2.3.4' > Profile__

*If you run cbd generate after this - you get the error*
__./Profile: line 1: 10.127.1.7: command not found__

*The corrected command is*
__echo 'PUBLIC_IP=1.2.3.4' > Profile__

For newbies like me, could you also add the following - since it took some time to figure out.
Login to the Cloudbreak UI by going to http://PUBLIC_IP:3000
The default username is __admin@example.com__ with the password __cloudbreak__.

**Comment by lalyos** [comment]
Hi,

Thanks for reporting it. Its already fixed on master but not yet released.

- The Profile instructions are here: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/deployer.bash#L100
- Cloudbreak ui and credentials: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/compose.bash#L31-L35

If you want to give it a try:
```
cbd update master
```

**Comment by cs905s** [comment]
Can we also update the README.md on Github?

**Comment by lalyos** [comment]
Did you try out the master version? it works like this:

![cbd start](http://s3-eu-west-1.amazonaws.com/sequenceiq/cbd-start.gif)

I think its much preferable that the tool writes actual values, rather than putting PUBLIC_IP into the realm.

**Comment by cs905s** [comment]
Cloud break not working after I did "cbd update master"
All the previous settings were deleted.
When I tried to create a new AWS credential - it is stuck at "creation in progress".
Cleaned out docker and started with a fresh cloud break-deployment directory.
Same issue.
cbd logs reveals that there are a lot of errors in the log related to periscope_1

**Comment by cs905s** [comment]
I think that CBD is too difficult to get up and running. After fixing periscope (using docker image 0.5.32), the next error was StackName should be 50 characters. I couldn't solve that - so I went back to the stable CBD (cbd update) but now that has an error __Caused by: org.hibernate.HibernateException: Missing column: kerberosAdmin in public.cluster__ in cloud break.
