### ISSUE TITLE
Clarify/implement 'cbd kill' vs 'cbd stop'

### ISSUE THREAD

**Issue by aperepel** [sequenceiq/cloudbreak-deployer#57]
There is a `cbd start` command, but no matching `cbd stop`. Please clarify if there's a way to gracefully stop containers and keep them around (e.g. do not remove them). If this doesn't make sense (containers are stateless, state in RDBMS, persisted in docker volumes), perhaps it makes sense to rename it to `cbd stop` and tone down the verbiage.

**Comment by mhmxs** [comment]
Hi @aperepel,

Sorry for the late answer, i'm clarifying issues and found this one. `cbd kill` is your friend, which terminates running containers.
