### ISSUE TITLE
Testing periscope alerts

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#63]
Hi,

I deployed a DIY cloudbreak instance in my aws instance and I am trying to test periscope to scale the cluster based on the alerts received from ambari.

In ambari UI page I see that few of the metrics of hdfs/yarn are not showing up. However the metrics under the Hbase page are showing up.

![hdfs-screenshot](https://cloud.githubusercontent.com/assets/2684148/7770313/c7154380-00aa-11e5-84cc-51509fb7f077.png) 
![yarn-screenshot](https://cloud.githubusercontent.com/assets/2684148/7770317/cf466ef8-00aa-11e5-98c5-8c859c326953.png)  
![hbase-screeenshot](https://cloud.githubusercontent.com/assets/2684148/7770318/d585f5fe-00aa-11e5-81df-6ca4b214cf6d.png)

Can somebody clarify if this is due to some misconfiguration?

I am using the blueprint : https://gist.github.com/malathit90/c7041df93ba7d9e6ca1e

Also the alerts such as DataNode Storage doesn't seem to be working. I wanted to trigger the alert and hence I followed the below steps:1) Logged on to the machine that has data node running.2) Logged on to the docker running ambari-agent3) changed user as hdfs4) created a file of size 1GB with dd command5) copied the file to HDFS storage twice
But the alert from ambari still shows as 0% however in the dashboard, I see that the DFS usage % increased.

The alert pages show 0% used:
![alert-page](https://cloud.githubusercontent.com/assets/2684148/7770325/e2c892f8-00aa-11e5-8be1-90f2b070bc95.png)  

However the alert in dashboard says otherwise:
![ambari dashboard](https://cloud.githubusercontent.com/assets/2684148/7770327/e630bf4c-00aa-11e5-960e-9f450ae5316c.png)

Is this a right approach to test periscope auto scale functionalities? If not please point me in the right direction?

Thanks,
Malathi

**Comment by lalyos** [comment]
@keyki could you please check this

**Comment by keyki** [comment]
There were 2 bugs:
* Ambari didn't show properly few metrics due to number conversion
* Cloudbreak suppressed the AMS metrics with the Baywatch project configuration

Both are fixed and working properly in the latest release.
