### ISSUE TITLE
OAuth2 authentication to identity server not working

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#64]
I am trying to make use of the rest api in cloudbreak and followed the steps as mentioned here:

http://blog.sequenceiq.com/blog/2014/11/06/securing-cloudbreak-with-oauth2-part-2/

I am able to get the access token, but am not able to access the rest api after that:

1) Getting access token using implicit method from cloudbreak-shell:
         curl -iX POST -H "accept: application/x-www-form-urlencoded" -d 'credentials={"username":"admin@example.com","password":"cloudbreak"}' "http://localhost:8089/oauth/authorize?response_type=token&client_id=cloudbreak_shell&scope.0=openid&redirect_uri=http://cloudbreak.shell"

2) Trying to access the api /user/stacks 
         curl -H "Authorization: Bearer <Token from step 1>" http://localhost:3000/user/stacks

After step 2 I get the error " POST request for "http://backend:8089/check_token" resulted in 400 (Bad Request); invoking error handler"

However when I tried to call check_token endpoint from curl I get a 200 response without any errors. Can somebody tell me what is that am missing here?

Thanks,
Malathi

**Comment by biharitomi** [comment]
Hi Malathi,

In your second step you try to connect to the Uluwatu component that is listening on port 3000.
So you have to direct your curl commands to the Cloudbreak component's API which is listening on the port 8080.
(curl -H "Authorization: Bearer TOKEN_FROM_FIRST_STEP" http://localhost:8080/user/stacks)

Br,
Tamas

**Comment by malathit90** [comment]
Thanks Tamas. It worked.
