### ISSUE TITLE
what happens when I shutdown the system while cloudbreak docker containers are running?

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#66]
I have the cloudbreak installed in a  AWS instance and it is made to stop everyday by 7.00 P.M. So will there be a problem if the docker containers of cloudbreak, periscope and sultans, etc runs while the system is shutdown? I meant to ask will there be corruption in the images?

Thanks,
Malathi

**Comment by martonsereg** [comment]
I think it won't be a problem until there is no ongoing operation when the system shuts down. Cloudbreak currently doesn't support recover logic for these long running operations (https://github.com/sequenceiq/cloudbreak/issues/596).

**Comment by malathit90** [comment]
Thanks for the reply. In future this issue will be resolved?

Thanks,
Malathi

**Comment by lalyos** [comment]
closing it, as the feature request is tracked at cloudbreak: sequenceiq/cloudbreak#596
