### ISSUE TITLE
Not able to create a file using webHDFS

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#67]
I have installed my hadoop cluster using cloudbreak and then I wanted to install hue with the cluster. After installing hue, I found that I was not able to upload a new file usinh the file browser. Hence I tried accessing the webHDFS as follows:

curl -i -L -X PUT "http://hdfs-host:50070/webhdfs/v1/tmp/test.txt?op=CREATE&overwrite=true&blocksize=4&replication=2&permission=0644&buffersize=24"
HTTP/1.1 307 TEMPORARY_REDIRECT
Cache-Control: no-cache
Expires: Mon, 01 Jun 2015 11:36:14 GMT
Date: Mon, 01 Jun 2015 11:36:14 GMT
Pragma: no-cache
Expires: Mon, 01 Jun 2015 11:36:14 GMT
Date: Mon, 01 Jun 2015 11:36:14 GMT
Pragma: no-cache
Location: http://ip-172-31-92-150.node.dc1.consul:50075/webhdfs/v1/tmp/test.txt?op=CREATE&namenoderpcaddress=ip-172-31-92-12.node.dc1.consul:8020&blocksize=4&buffersize=24&overwrite=true&permission=644&replication=2
Content-Type: application/octet-stream
Content-Length: 0
Server: Jetty(6.1.26.hwx)

curl: (6) Could not resolve host: ip-172-31-92-150.node.dc1.consul

After the initial redirect from the namenode to wite the data node, the data node's IP address is not resolvable. Can somebody help me how this issue can be resolved?

Thanks,
Malathi

**Comment by malathit90** [comment]
I tried running the curl inside the docker container running the namenode and things work fine. I hope it is because the hostname of datanode is not resolvable outside the container. Is this a bug in the system?

Thanks,
Malathi

**Comment by malathit90** [comment]
The same problem exists while accessing the mapreduce job logs via resource manager UI.

**Comment by malathit90** [comment]
The issue can be reproduced as follows:

Go to namenode UI and select Utilities -> Browse files. Then try to download any of the files present in HDFS. The page redirects to the address such as http://ip-172-31-92-103.node.dc1.consul:50075, which is not resolvable from my machine.

**Comment by biharitomi** [comment]
Hi,

This is not a bug, Cloudbreak provisions the Hadoop clusters with internal domain names that are managed by consul and these addresses could be reached internally, so if you ssh to the machine of Ambari server you could ping and reach them.

In that case you would like to connect to these components from your local machine, you could get the public-private address pairs of the appropriate component's node from the Ambari server by reaching the '*$AMBARI_SERVER_ADDRESS/api/v1/hosts?fields=Hosts/host_name,Hosts/public_host_name*'.

We are just redesigning our security model and in the near future all of the ports will be closed by default except the Ambari UI, so probably further configuration will be necessary.

Br,
Tamas

**Comment by malathit90** [comment]
Thanks for the explanation.
