### ISSUE TITLE
Explanation of sync option available in cluster

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#78]
Hi,

Today morning I updated cloudbreak deployer to master branch changes. After that I noticed that there is an option called sync as shown below

![screenshot from 2015-06-15 15 41 30](https://cloud.githubusercontent.com/assets/2684148/8157796/207e6ea6-1375-11e5-9902-436e63587a50.png)

Can somebody explain the functionality of the option?

**Comment by doktoric** [comment]
Hi,

This function helps to synchronize the cluster state which was modified not with cloudbreak for example if you doing something by your hand on aws console for example stopping an instance and click on this button then the cluster will be in stopped state(This will be a future improvement).
Currently If an error occured under the stop phase or in the start then this function can modify your cluster state based on some healthcheck.
