### ISSUE TITLE
cannot create cluster after upgrading cbd

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#81]
I recently upgraded from 0.5.2 to 0.5.3 version of cloudbreak deployer. After that I cannot create clusters via cloudbreak. I get the IndexOutOfBounds exception. Can somebody help me resolve the error? I tried running the below commands after upgrading.

1) cbd kill
2) cbd delete
3) cbd start
4) cbd migrate
5) cbd startdb

cloudbreak_1 | 2015-06-26 06:37:19,595 [http-nio-8080-exec-2] prepareImage:108 INFO  c.s.c.s.d.StackDecorator - [owner:undefined] [type:STACK] [id:undefined] [name:temp-cluster] Selected VM image for CloudPlatform 'AWS' is: ami-9b876af0
cloudbreak_1 | 2015-06-26 06:37:19,712 [threadPoolExecutorDispatcher-1] accept:44 DEBUG c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Executing flow Logic on the event: Event{id=null, headers=null, replyTo=null, key=PROVISIONING_SETUP, data=ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}}
cloudbreak_1 | 2015-06-26 06:37:19,712 [threadPoolExecutorDispatcher-1] execute:20 INFO  c.s.c.c.f.h.ProvisioningSetupHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Executing provisioning setup logic. Event: Event{id=null, headers=null, replyTo=null, key=PROVISIONING_SETUP, data=ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}}
cloudbreak_1 | 2015-06-26 06:37:19,712 [threadPoolExecutorDispatcher-1] setup:53 DEBUG c.s.c.c.f.s.SimpleFlowFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Provisioning setup. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:19,743 [threadPoolExecutorDispatcher-1] setup:60 DEBUG c.s.c.c.f.s.SimpleFlowFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Provisioning setup DONE.
cloudbreak_1 | 2015-06-26 06:37:19,743 [threadPoolExecutorDispatcher-1] assemblePayload:116 INFO  c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Default service result decoration for class com.sequenceiq.cloudbreak.core.flow.handlers.ProvisioningSetupHandler
cloudbreak_1 | 2015-06-26 06:37:19,743 [threadPoolExecutorDispatcher-1] transitionForClass:39 DEBUG c.s.c.c.f.s.SimpleTransitionKeyService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Retrieving transition for class: class com.sequenceiq.cloudbreak.core.flow.handlers.ProvisioningSetupHandler
cloudbreak_1 | 2015-06-26 06:37:19,744 [threadPoolExecutorDispatcher-1] successKey:21 INFO  c.s.c.c.f.s.SimpleTransitionKeyService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Transitioning from phase [PROVISIONING_SETUP] to [PROVISIONING]
cloudbreak_1 | 2015-06-26 06:37:19,744 [threadPoolExecutorDispatcher-2] accept:44 DEBUG c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Executing flow Logic on the event: Event{id=null, headers=null, replyTo=null, key=PROVISIONING, data=ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}}
cloudbreak_1 | 2015-06-26 06:37:19,745 [threadPoolExecutorDispatcher-2] execute:20 DEBUG c.s.c.c.f.h.ProvisioningHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Executing provisioning logic. Event: Event{id=null, headers=null, replyTo=null, key=PROVISIONING, data=ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}}
cloudbreak_1 | 2015-06-26 06:37:19,745 [threadPoolExecutorDispatcher-2] provision:73 DEBUG c.s.c.c.f.s.SimpleFlowFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Provisioning. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:19,785 [threadPoolExecutorDispatcher-2] logBefore:578 DEBUG c.s.c.c.f.s.SimpleStackFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Provisioning stack [STACK_FLOW_STEP] [STARTED]. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:19,785 [threadPoolExecutorDispatcher-2] fireCloudbreakEvent:45 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Firing Cloudbreak event: CloudbreakEventData{entityId=50, eventType='UPDATE_IN_PROGRESS', eventMessage='Provisioning stack started.'}
cloudbreak_1 | 2015-06-26 06:37:19,786 [threadPoolExecutorDispatcher-2] provision:365 DEBUG c.s.c.c.f.s.SimpleStackFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Provision stack [FLOW_STEP] [STARTED]. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:19,818 [threadPoolExecutorDispatcher-3] populateClusterData:122 DEBUG c.s.c.s.e.DefaultCloudbreakEventService - [owner:undefined] [type:CLOUDBREAKEVENTDATA] [id:undefined] [name:undefined] No cluster data available for the stack: 50
cloudbreak_1 | 2015-06-26 06:37:19,878 [threadPoolExecutorDispatcher-3] createStackEvent:68 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:undefined] [type:CLOUDBREAKEVENTDATA] [id:undefined] [name:undefined] Event and notification from the event were created: CloudbreakEvent{id=5, eventType='UPDATE_IN_PROGRESS', eventTimestamp=Fri Jun 26 06:37:19 UTC 2015, eventMessage='Provisioning stack started.', owner='719d6839-9ccc-429c-bb9b-3780f8df8fd7', account='seq1234567', cloud='AWS', region='US_EAST_1', blueprintName='null', instanceGroup='null', blueprintId=0, stackId=50}
cloudbreak_1 | 2015-06-26 06:37:19,981 [threadPoolExecutorDispatcher-2] createCloudFormationClient:40 DEBUG c.s.c.s.s.c.a.AwsStackUtil - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Amazon CloudFormation client successfully created.
cloudbreak_1 | 2015-06-26 06:37:19,989 [threadPoolExecutorDispatcher-2] createEC2Client:54 DEBUG c.s.c.s.s.c.a.AwsStackUtil - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Amazon EC2 client successfully created.
cloudbreak_1 | 2015-06-26 06:37:20,054 [threadPoolExecutorDispatcher-2] createAutoScalingClient:64 DEBUG c.s.c.s.s.c.a.AwsStackUtil - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Amazon Autoscaling client successfully created.
cloudbreak_1 | 2015-06-26 06:37:20,178 [threadPoolExecutorDispatcher-2] doAddResources:191 INFO  c.s.c.r.RetryingStackUpdater - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Updated stack resources.
cloudbreak_1 | 2015-06-26 06:37:20,374 [http-nio-8080-exec-6] decorate:56 DEBUG c.s.c.s.d.HostGroupDecorator - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:springLog] [id:] [name:] Decorating hostgroup on [POST] request.
cloudbreak_1 | 2015-06-26 06:37:20,386 [http-nio-8080-exec-6] decorate:56 DEBUG c.s.c.s.d.HostGroupDecorator - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:springLog] [id:] [name:] Decorating hostgroup on [POST] request.
cloudbreak_1 | 2015-06-26 06:37:20,395 [http-nio-8080-exec-6] create:104 INFO  c.s.c.s.c.AmbariClusterService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:springLog] [id:] [name:] Cluster requested [BlueprintId: 53]
cloudbreak_1 | 2015-06-26 06:37:20,482 [threadPoolExecutorDispatcher-2] createEC2Client:54 DEBUG c.s.c.s.s.c.a.AwsStackUtil - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Amazon EC2 client successfully created.
cloudbreak_1 | 2015-06-26 06:37:20,545 [threadPoolExecutorDispatcher-2] provision:378 ERROR c.s.c.c.f.s.SimpleStackFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Exception during the stack stop requested process: Index: 0, Size: 0
cloudbreak_1 | 2015-06-26 06:37:20,546 [threadPoolExecutorDispatcher-2] provision:85 ERROR c.s.c.c.f.s.SimpleFlowFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Exception during provisioning setup: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
cloudbreak_1 | 2015-06-26 06:37:20,546 [threadPoolExecutorDispatcher-2] consumeError:104 DEBUG c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Default error consumption logic for exception: 
cloudbreak_1 | 2015-06-26 06:37:20,546 [threadPoolExecutorDispatcher-2] accept:21 DEBUG c.s.c.c.f.CloudbreakErrorHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Consuming error:
cloudbreak_1 | 2015-06-26 06:37:20,547 [threadPoolExecutorDispatcher-2] errorLogic:31 INFO  c.s.c.c.f.CloudbreakErrorHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Default error consumption logic: Do nothing. Exception message: com.sequenceiq.cloudbreak.core.CloudbreakException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
cloudbreak_1 | 2015-06-26 06:37:20,547 [threadPoolExecutorDispatcher-2] handleErrorFlow:91 DEBUG c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Default error flow handling for class com.sequenceiq.cloudbreak.core.flow.handlers.ProvisioningHandler
cloudbreak_1 | 2015-06-26 06:37:20,548 [threadPoolExecutorDispatcher-2] assemblePayload:116 INFO  c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Default service result decoration for class com.sequenceiq.cloudbreak.core.flow.handlers.ProvisioningHandler
cloudbreak_1 | 2015-06-26 06:37:20,548 [threadPoolExecutorDispatcher-2] transitionForClass:39 DEBUG c.s.c.c.f.s.SimpleTransitionKeyService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Retrieving transition for class: class com.sequenceiq.cloudbreak.core.flow.handlers.ProvisioningHandler
cloudbreak_1 | 2015-06-26 06:37:20,548 [threadPoolExecutorDispatcher-2] failureKey:28 INFO  c.s.c.c.f.s.SimpleTransitionKeyService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Transitioning from phase [PROVISIONING] to [STACK_CREATION_FAILED]
cloudbreak_1 | 2015-06-26 06:37:20,549 [threadPoolExecutorDispatcher-4] accept:44 DEBUG c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Executing flow Logic on the event: Event{id=null, headers=null, replyTo=null, key=STACK_CREATION_FAILED, data=ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}}
cloudbreak_1 | 2015-06-26 06:37:20,549 [threadPoolExecutorDispatcher-4] execute:20 INFO  c.s.c.c.f.h.StackCreationFailureHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] execute() for phase: STACK_CREATION_FAILED
cloudbreak_1 | 2015-06-26 06:37:20,550 [threadPoolExecutorDispatcher-4] handleStackCreationFailure:173 DEBUG c.s.c.c.f.s.SimpleFlowFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Stack creation failed. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:20,572 [threadPoolExecutorDispatcher-4] logBefore:578 DEBUG c.s.c.c.f.s.SimpleStackFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Creation of infrastructure failed [STACK_FLOW_STEP] [STARTED]. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:20,573 [threadPoolExecutorDispatcher-4] fireCloudbreakEvent:45 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Firing Cloudbreak event: CloudbreakEventData{entityId=50, eventType='UPDATE_IN_PROGRESS', eventMessage='Creation of infrastructure failed started.'}
cloudbreak_1 | 2015-06-26 06:37:20,622 [threadPoolExecutorDispatcher-5] createStackEvent:68 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:undefined] [type:CLOUDBREAKEVENTDATA] [id:undefined] [name:undefined] Event and notification from the event were created: CloudbreakEvent{id=10, eventType='UPDATE_IN_PROGRESS', eventTimestamp=Fri Jun 26 06:37:20 UTC 2015, eventMessage='Creation of infrastructure failed started.', owner='719d6839-9ccc-429c-bb9b-3780f8df8fd7', account='seq1234567', cloud='AWS', region='US_EAST_1', blueprintName='multi-node-hdfs-yarn-falcon', instanceGroup='null', blueprintId=53, stackId=50}
cloudbreak_1 | 2015-06-26 06:37:20,641 [threadPoolExecutorDispatcher-4] fireCloudbreakEvent:45 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Firing Cloudbreak event: CloudbreakEventData{entityId=50, eventType='BILLING_STOPPED', eventMessage='Stack creation failed.'}
cloudbreak_1 | 2015-06-26 06:37:20,691 [threadPoolExecutorDispatcher-6] createStackEvent:68 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:undefined] [type:CLOUDBREAKEVENTDATA] [id:undefined] [name:undefined] Event and notification from the event were created: CloudbreakEvent{id=11, eventType='BILLING_STOPPED', eventTimestamp=Fri Jun 26 06:37:20 UTC 2015, eventMessage='Stack creation failed.', owner='719d6839-9ccc-429c-bb9b-3780f8df8fd7', account='seq1234567', cloud='AWS', region='US_EAST_1', blueprintName='multi-node-hdfs-yarn-falcon', instanceGroup='null', blueprintId=53, stackId=50}
cloudbreak_1 | 2015-06-26 06:37:20,709 [threadPoolExecutorDispatcher-4] doUpdateStackStatus:95 INFO  c.s.c.r.RetryingStackUpdater - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Updated stack: [status: 'CREATE_FAILED', statusReason: 'com.sequenceiq.cloudbreak.core.CloudbreakException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0'].
cloudbreak_1 | 2015-06-26 06:37:20,709 [threadPoolExecutorDispatcher-4] fireCloudbreakEvent:45 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Firing Cloudbreak event: CloudbreakEventData{entityId=50, eventType='CREATE_FAILED', eventMessage='com.sequenceiq.cloudbreak.core.CloudbreakException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0'}
cloudbreak_1 | 2015-06-26 06:37:20,709 [threadPoolExecutorDispatcher-4] logAfter:583 DEBUG c.s.c.c.f.s.SimpleStackFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Creation of infrastructure failed [STACK_FLOW_STEP] [FINISHED]. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:20,710 [threadPoolExecutorDispatcher-4] fireCloudbreakEvent:45 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Firing Cloudbreak event: CloudbreakEventData{entityId=50, eventType='CREATE_FAILED', eventMessage='Creation of infrastructure failed finished.'}
cloudbreak_1 | 2015-06-26 06:37:20,711 [threadPoolExecutorDispatcher-4] handleStackCreationFailure:176 DEBUG c.s.c.c.f.s.SimpleFlowFacade - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Stack creation failure handled.
cloudbreak_1 | 2015-06-26 06:37:20,711 [threadPoolExecutorDispatcher-4] execute:22 INFO  c.s.c.c.f.h.StackCreationFailureHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Stack creation failure  handled. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}
cloudbreak_1 | 2015-06-26 06:37:20,711 [threadPoolExecutorDispatcher-4] assemblePayload:116 INFO  c.s.c.c.f.AbstractFlowHandler - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Default service result decoration for class com.sequenceiq.cloudbreak.core.flow.handlers.StackCreationFailureHandler
cloudbreak_1 | 2015-06-26 06:37:20,712 [threadPoolExecutorDispatcher-4] transitionForClass:39 DEBUG c.s.c.c.f.s.SimpleTransitionKeyService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Retrieving transition for class: class com.sequenceiq.cloudbreak.core.flow.handlers.StackCreationFailureHandler
cloudbreak_1 | 2015-06-26 06:37:20,712 [threadPoolExecutorDispatcher-4] successKey:21 INFO  c.s.c.c.f.s.SimpleTransitionKeyService - [owner:719d6839-9ccc-429c-bb9b-3780f8df8fd7] [type:STACK] [id:50] [name:temp-cluster] Transitioning from phase [STACK_CREATION_FAILED] to [NONE]

**Comment by lalyos** [comment]
closing outdated cbd issue. please reopen if it still happens with latest version.
